# -*- coding: utf-8 -*-
"""time _seriese

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yw7N10rRb8RMoKFEpK1YhlgRv3yxoYy_
"""

import pandas as pd

import pandas as pd 
import numpy as np



#data = pd.read_csv('')

pip install prophet

#@title Default title text
avocado = pd.read_csv('/content/avocado.csv')

"""# New section"""

avocado

avocado.info

avocado = avocado.sort_values('Date')

avocado

import matplotlib.pyplot as plt

plt.plot(avocado['Date'],avocado['AveragePrice'])

avocado_ts = avocado[['Date','AveragePrice']]

avocado_ts.columns = ['ds','y']

avocado_ts

from prophet import Prophet

m = Prophet()

m.fit(avocado_ts)

future= m.make_future_dataframe(periods=365)

forcast = m.predict(future)

forcast

fig_1 =m.plot(forcast)
fig_1

fig_2= m.plot_components(forcast)
fig_2

## thanks